In [4]:
import numpy as np

In [5]:
#Creating a matrix with chaining functions
a = np.arange(1,10).reshape((3,3))
#reshape converts the array to m*n matrix as required and arange function works similar to the range function as in normal python

In [6]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#linspace function divides the elements between 2 numbers with equal jumps. Note that unlike range end number is inclusive
b = np.linspace(1,10,20)
print(b)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [5]:
#In the above piece of code if you note 1 and 10 are inclusive and there are 20 values generated with equal intervals

In [8]:
#Transposing a matrix, simply use desiredmatrix.T for the same

In [7]:
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
#flatten() flattens the matrix to 1D list
b = a.T.flatten()

In [9]:
print(b)

[1 4 7 2 5 8 3 6 9]


In [10]:
a.ndim

2

In [13]:
# ndim gives the dimension of the array, where as .shape gives the number of rows and columns of the array

In [14]:
a.shape

(3, 3)

In [15]:
#2D array slicing

In [16]:
#If you want to access a specifc row or column, it means that you will have to access all the elements in that specific column and row respectively

In [17]:
#Let's say you would want to access 2nd row (as per 0 indexing it is 1st)

In [19]:
a[1,:]

array([4, 5, 6])

In [20]:
#Similarly if you want access 2nd column

In [23]:
a[:,1]

array([2, 5, 8])

In [24]:
#Let's say if you want to access a specific subset of the Matrix (elements: 2,3,5,6)

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
#In the above example we wanted to access first 2 rows but only 2nd and 3rd column

In [29]:
#If we want to access elements(1,3,7,9)

In [30]:
a[::2,::2]

array([[1, 3],
       [7, 9]])

In [31]:
#Here we had to give a "step" or "jump" argument as well which "2" in this case